### ISSUE TITLE
"Device errored while trying to connect: Device does not have endpoint rx" on lovense device reconnects on windows

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug#428]
**Describe the bug**
1. Connect a lovense device to Buttplug via intiface cli 
2. Cycle power on lovense device

**Expected behavior**
Device reconnects successfully

**Actual behavior**
Every so often, characteristic enumeration will fail, which causes the device to be dropped. However, it seems that btleplug may not handle disposal of services/characteristics correctly, meaning that the device stays connected even though we've dropped it. This requires the user to turn the device off and on again, or to stop the process, in order to try again.

**Comment by blackspherefollower** [comment]
There's a possibility that this may be the same weirdness in the characteristic discovery I was encountering working on the Satisfyer/MagicMotion issue, and could be resolved by https://github.com/deviceplug/btleplug/pull/247

**Comment by qdot** [comment]
Hopefully fixed in v6? Marking as such, if we keep seeing it I'll reopen.

**Comment by ValerieOSD** [comment]
this still happening on the latest release version i was able to find (buttplug-rs-ffi-lib v2.0.4)
maybe u guys have a newer version of the library where it's fixed? i can't find it in that case, soz

**Comment by qdot** [comment]
@ValerieOSD buttplug-rs-ffi-lib hasn't been built in several years and is no longer part of the project, so I have no idea what you're talking about?
